
= Hyperparameter Optimization Demo

*Goal:* Plug your DNN, search, and data into CANDLE/Supervisor.

== Git clones

. Benchmarks: git@github.com:ECP-CANDLE/Benchmarks.git +
  Checkout branch release_01
. Supervisor: git@github.com:ECP-CANDLE/Supervisor.git +
  Use branch master

== Edits 

Edit the Supervisor configuration scripts to handle your case:

. Point Supervisor to your CANDLE-compliant DNN: +
  Edit workflows/mlrmbo/test/test-1.sh:
.. Set MODEL_PYTHON_SCRIPT to cc_t29res +
   This is just the name of your Python script
.. Set MODEL_PYTHON_DIR to $HOME/.../1_migrating_your_DNN_to_candle +
   This is inserted into PYTHONPATH so that your Python script can be found
. Set up your search space: +
  Edit workflows/mlrmbo/test/cfg-prm-1.sh:
.. Set PARAM_SET_FILE to $EMEWS_PROJECT_ROOT/data/nt3_hps_exp_01.R
.. You can edit nt3_hps_exp_01.R
. Set your data location: +
  Edit 1_migrating_your_DNN_to_candle/t29_default_model.txt for Theta:
.. Set: +
   train_path=/projects/Candle_ECP/wozniak/data/t29/rip.it.train.csv
.. Set: +   
   test_path=/projects/Candle_ECP/wozniak/data/t29/rip.it.test.csv
. Run it! +
   mlrmbo/test/test-1.sh 000 theta -a
